### ISSUE TITLE
burst-pool config of different port doesnt work, still use 8124

### ISSUE THREAD

**Issue by Pascal66** [guelz/burst-pool#4]
Miner:
"Mode" : "pool",
"Server" : "192.168.1.42",
"Port" : 8234
,pool-config.js :
poolDiff : 1000000,
poolDiffCurve : 0.75,
poolPort : 8234,

**Comment by guelz** [comment]
Sorry, still didn't have the time to confirm that! 
Are you sure that the port does not get blocked by some firewall or something?

**Comment by guelz** [comment]
Just tried.... works alright for me!?

**Comment by guelz** [comment]
Just tried.... works alright for me!?  (port:8224)

**Comment by Pascal66** [comment]
port 8224 ?!

**Comment by guelz** [comment]
just randomly (and lazy) chosen....
