### ISSUE TITLE
Why cant I use a external wallet ?

### ISSUE THREAD

**Issue by Pascal66** [guelz/burst-pool#5]
If I wish to use the 'standard' wallet like that in config.js : 
module.exports = {
    wallets : [
		{
            walletIP : 'pool.burst-team.us',
            walletPort : 8125,
            walletUrl : 'pool.burst-team.us:8125'
        }
    ],
this doesnt work (this doesnt work too if I use a wallet in an localnetwork based computer)

**Comment by guelz** [comment]
it works allright if you use their IP-Address:  
wallets : [
        {
            walletIP : '216.165.179.45',
            walletPort : 8125,
            walletUrl : 'http://216.165.179.45:8125'
        }

**BUT** it totally makes no sense on so many levels!!
- "ninjas" tend to be a bit overloaded most of the time! (and this is timing sensitive!)
- you'll be constantly sending your Passphrase over an unencrypted connection!
- the Burst Network needs more Nodes!!! 

I'd prefer if everybody would be running a Wallet e.g. Node even when pool mining! Because I assume that forking would be much less of en issue if there would be more "diversity" and not everybody depending on just a few nodes!
I know the wallet needs quite a bit of RAM which can be annoying on small machines, but still "more nodes=better!" 
The wallet of my little solomining-pool (?!) has been uploading 15GB over the past 4 weeks so there's clearly a need for nodes!

Men, I never used that many ! in one post!-)

**Comment by Pascal66** [comment]
No sense..
I've some counter good senses to do that:
- Using a stable wallet from someone wich can be trusted 
- Using a 5Go database (and growing exponantialy) without having to wait 10days 
- more 'peers' is better, not more nodes (wich is exactly the same ? not really...)
Your are right, when you say that you need more nodes, so for that, It can be usefull to make pool server less 'cryptic config' than let a few other taking fee with some stupid mods of the original pool.

IE make pools growing, that make wallets online growing, that make nodes growing.
If I cant made my pool working, I stop to have a wallet and node and peer online. And just using other pool as it.

**Comment by Pascal66** [comment]
btw, it doesnt work here : 
round #undefined diff NaN, elapsed in 14 days, 0 Miners, total shares 0.00, best deadline -1 from 0

**Comment by Pascal66** [comment]
you'll be constantly sending your Passphrase over an unencrypted connection!
Really ?! How ? In which js ? I've see this somewhere

**Comment by Pascal66** [comment]
The wallet of my little solomining-pool (?!) has been uploading 15GB over the past 4 weeks so there's clearly a need for nodes!
Can you share your valid config.js ?

**Comment by guelz** [comment]
first of, I'm doing this only for a hobby without any profesional knowledge of anything related!
Also, English is not my first language! If you wana flame me for that, go ahead, I can take it!-)

Second:
- I do have trust in them! However when it comes to forking I'd rather have it in my own Hands.

- Download the a max 24h old DB from the [Forums](https://forums.burst-team.us/topic/45/burst-blockchain-ddl-updated-regular-every-24h-zipped)

- Did I get that wrong?! I'm committing my Deadlines to the Network, then I'm a Node aren't I? 

-If you dont want donate, just turn it off.

-Sorry, I dont know whats going wrong with your setup. (>see bold text below!)

-When running a pool or do solo mining you need to "login" to the wallet each time your "comitting" a Deadline. So your Passphrase gets sent. Pleas go to the Forums and ask someone more knowable for a better explanation.

-Sure! current config (for testing):

> module.exports = {
    wallets : [
        {
            walletIP : '127.0.0.1',
            walletPort : 8125,
            walletUrl : 'http://127.0.0.1:8125'
        }
    ],
    redirection : {
        enabled : false,
        target : 'http://lhc.ddns.net:8124'
    },
    walletIndex: 0,
    blockMature : 1,
    txFeePercent : 0.0005,
	  devFee : false,
	  devFeePercent : 0.01,
    poolFee : 0.0,
    poolDiff : 1000000,
    poolDiffCurve : 0.75,
    poolPort : 8224,
    poolPvtKey : 'pony engine iam not gona put my passphrase here ',
     poolPublicRS : 'BURST-995S-DBT2-T4UB-H4N5E',
       poolPublic : '17730252107975728248',
       poolFeePaymentAddr : '14176614198960711717',
    defaultPaymentDeadline : 1440,
    poolFeePaymentTxFeeNQT : 100000000,
    httpPort : 8080,
    websocketPort : 4443,
    enablePayment : true,
    minimumPayout : 0.0,
    clearingMinPayout : 2.0,
    lastSessionFile : 'last-session.json',
    cumulativeFundReduction : 0.5,
    logWebsocketToConsole : false,
    maxRoundCount : 500,
    sharePenalty : 0.00,
    maxRecentPaymentHistory : 50
};


-and [wallet peers](https://i.imgsafe.org/cf43daf8af.jpg)

**btw. I just remembered: what version of node.js are you running?!
This code (is so old) is only running up to v5.12.0 !! as someone in the [Forums](https://forums.burst-team.us/topic/2643/lex-pool-a-rewritten-pool-based-on-uray-source) mentioned!  I'm running 4.7.0** 

I know this code is old, not well maintained nor documented! I's a bit frustrating!!
But with no coding knowledge myself I depend on other people.   I'm just trying to do a little "cleanup fork" here on github.
But come on over to the Forums! People are very helpful there. You'll find me under the username "nixxda"

**Comment by Pascal66** [comment]
-btw. I just remembered: what version of node.js are you running?!
This code (is so old) is only running up to v5.12.0 !! as someone in the Forums mentioned! I'm running 4.7.0
node 6.9.1

- first of, I'm doing this only for a hobby without any profesional knowledge of anything related!
Also, English is not my first language! If you wana flame me for that, go ahead, I can take it!-)
I'm poor in english too, , I never flame anyone who's make a decent work/fork

Second:

Download the a max 24h old DB from the Forums
Always

Did I get that wrong?! I'm committing my Deadlines to the Network, then I'm a Node aren't I?
Sure

-If you dont want donate, just turn it off.
I want to donate to anything working well

-Sorry, I dont know whats going wrong with your setup. (>see bold text below!)
I dont know too

-When running a pool or do solo mining you need to "login" to the wallet each time your "comitting" a Deadline. So your Passphrase gets sent. Pleas go to the Forums and ask someone more knowable for a better explanation.
Understand you

-I'm just trying to do a little "cleanup fork" here on github.
Thank you so much for that

**Comment by guelz** [comment]
Here you go!-) I was abel to help! **Use node.js 4.7.1 =last LTS**
I also open a Issue on the Repo I forked for this......!

**Comment by Pascal66** [comment]
Sorry but cant downgrade my node... All my nodes scripts need the latest.
I understand why somethings are not working well. but not sure, i've not the time to read the code for the moment.
Maybe I bother you too much because of a different version of node and npm

**Comment by guelz** [comment]
nvm can do something like that. I think its `nvm run 4.7.1 --version`
you can have multiple versions of node installed with nvm. but I never tried just running one program with  an other version! I always used it with 'nvm use -g 4.7.1' for "global"

**Comment by SOELexicon** [comment]
as the original author of most of this code. i would strongly advise not using an online wallet.

why you may ask.

well because when you have 70 + miners submitting 3 deadlines each in under a minute. the response times on the web wallet are something like 500ms compared to 150 ms for submit nonce. now multiply that difference by the amount of submissions you have and your going to have a huge problem.

also your not just worrying about the response times. generally those wallets take a hammoring from any online users. also the andriod wallet now uses them to.

just a few things i thought i would mention.

if you have any more questions please post them on the github located at https://github.com/SOELexicon/burst-pool as i get notifications for these.

**Comment by SOELexicon** [comment]
@Pascal66 you can use up to node V5.12.0. V6 and above have changed a lot of things which breaks a few functions. i can fix these if enough people have the issue where they need to use V6 but currently your the only person.

the version im running at http://burst.lexitoshi.uk is running on node V6 and ive already changed all the problem code for this however this isnt public yet. and was only upgraded so i could integrate node modules that dont exist in V5 or 4

**Comment by Pascal66** [comment]
👍 the goal wasnt to use a external wallet like the one i've mentionned, but the one in another computer in a local newtork, wich make sens, and wich doesnt work, so I dont know why your v6 isnt released wich can make many people happy. I close this issue and then open a new at soel
